import { createContext, useState } from 'react'
import { ThreeCircles } from 'react-loader-spinner'

export const LagContext = createContext({})

export function UserProvider( {children} ) {     
    const [products, seProducts] = useState(
        [
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
            {title: "Residente Evil 4", description: "Um surto de uma mutação do fungo Cordyceps arrasa os Estados Unidos em setembro de 2013, transformando seus hospedeiros humanos em monstros canibalísticos chamados de Infectados. Joel foge do caos dos subúrbios de Austin, Texas, junto com seu irmão Tommy e sua filha Sarah. Esta acaba baleada por um soldado durante a fuga e morre nos braços do pai.[17] A maior parte da civilização humana acaba destruída no decorrer dos vinte anos seguintes. Sobreviventes vivem em zonas de quarentena altamente policiadas, em assentamentos independentes e em grupos nômades. Joel passa a trabalhar como contrabandista junto com sua parceira Tess na zona de quarentena de Boston, Massachusetts, uma das últimas ainda funcionando. Eles caçam Robert, um comerciante do mercado negro, a fim de recuperar um carregamento roubado de armas. Robert é morto por Tess, porém antes revela ter trocado as armas com os Vaga-Lumes, uma milícia rebelde que se opõe às autoridades da zona de quarentena.", cape: "https://www.psu.com/wp/wp-content/uploads/2022/06/ResidentEvil4-Remake-PS5-Wallpapers-0.jpg", background: "https://wallpapercave.com/wp/wp1811272.jpg", value: 100},
        ]
    )
    const load = <ThreeCircles
        height="100"
        width="100"
        color="#4fa94d"
        wrapperStyle={{}}
        wrapperClass=""
        visible={true}
        ariaLabel="three-circles-rotating"
        outerCircleColor=""
        innerCircleColor=""
        middleCircleColor=""
    />

  return (
    <LagContext.Provider value={{
        products,
        seProducts,
        load        
    }}>
      {children}
    </LagContext.Provider>
  )
}